version: '3.8'
services:
  bot:
    build: .
    volumes:
      - ./config.json:/app/config.json
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "node", "-e", "new WebSocket('wss://zkillboard.com/websocket/')"]
      interval: 30s
      timeout: 10s
      retries: 3 